service: scrape-from-the-ape

provider:
  name: aws
  timeout: 300
  runtime: python3.8
  region: ${env:AWS_REGION}


functions:
  crawl:
    handler: spider.crawl
    include:
      - scrape_from_the_ape/**
    events:
      - schedule: rate(24 hours)


plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: true
